spring:
  application:
   name: order-rev

  kafka:
   bootstrap-servers: ${KAFKA_SERVER}

  mongodb:
   uri: ${MONGO_URL}


apps:
  collection: ${MONGO_COLLECTION_ORDER}
  new-order: ${NEW_ORDER_HEADER}
server:
  port: 8082